#!/usr/bin/python

import glob
import traceback
import os

import underscore
import test_utils

UNDERSCORE = './bin/underscore'

def runTests():
    for test_file in glob.glob('test_files/*py'):
        with test_utils.TestRun(test_file) as test_run:
            output_file = os.path.join('test_files', 'underscored', 
                                       os.path.basename(test_file) + '.us')
            underscore.compile(test_file, output_file=output_file, original=True)

            expected_output = test_run.execute(test_file)
            actual_output = test_run.execute(output_file)

            if actual_output != expected_output:
                raise AssertionError("Output Error\n" +
                                     "Expected:\n" + expected_output + 
                                     "Actual:\n" + actual_output)

         
def displayResults():
    for test_file, exc_info in test_utils.FAILURES.items():
        print "=" * 70
        print test_file
        print "=" * 70
        traceback.print_exception(*exc_info)

if __name__ == '__main__':
    print '=' * 70
    runTests()
    print
    displayResults()
