#!/usr/bin/python

import glob
import sys
import underscore
import re

from collections import defaultdict

FAILURES = defaultdict(set)
KEYWORDS = {'def', 'pass', 'print', 'global', 'if'}
BUILTINS = {'True', 'False', 'None'}
BAR = '=' * 70
IDENTIFER_REGEX = '[a-zA-Z][a-zA-Z0-9]*'


def testCase(filename):
    passed = True
    _ = underscore.compile(filename)
    for _id in re.findall(IDENTIFER_REGEX, _):
        if _id not in KEYWORDS | BUILTINS:
            if  _id != '_' * len(_id):
                passed = False
                FAILURES[filename].add(_id)
                sys.stderr.write('F')

    if passed:
        sys.stderr.write('.')


def testAll():
    for filename in glob.glob('test_files/*.py'):
        testCase(filename)


if __name__ == '__main__':
    sys.stderr.write(BAR + '\n')
    testAll()
    sys.stderr.write('\n')

    if FAILURES:
        sys.stderr.write(BAR + '\n')
        sys.stderr.write('Problems in these files\n')
        sys.stderr.write('\n')
        for filename, used in FAILURES.items():
            sys.stderr.write(filename + ' has indentifer(s)\n')
            sys.stderr.write(', '.join(used))
            sys.stderr.write('\n')
        sys.stderr.write('\n\n')
        
